version: "3.7"
services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    networks:
      binliz-com-network:
    volumes:
      - ./nginx/templates:/etc/nginx/templates:rw,cached
      - ./src:/app:rw
    env_file:
      - .env
    restart: always
    links:
      - fpm
  fpm:
    build:
      context: .
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
        - USER=${USER:-binliz}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./src:/app
    restart: always
    networks:
      binliz-com-network:
    env_file:
      - .env

networks:
  binliz-com-network:
